"""Unit effectiveness data derived from OpenRA Red Alert weapon definitions.

Auto-generated by scripts/generate_damage_matrix.py from the OpenRA
MiniYAML weapon and unit definitions. Do not edit manually — re-run
the generator script instead.

Armor types in RA:
  - none:     Infantry (unarmored)
  - light:    Light vehicles, helicopters, aircraft, submarines
  - heavy:    Tanks, heavy vehicles, destroyers, transports
  - wood:     Wooden structures (barracks, power plants, etc.)
  - concrete: Concrete structures (walls)

Versus percentage: 100 = normal damage, >100 = bonus, <100 = penalty.
Values are expressed as multipliers (1.0 = 100%).
"""

from typing import Optional

# ────────────────────────────────────────────────────────────────────────────
# Armor type for each unit (from Armor: Type: in rules YAML)

UNIT_ARMOR: dict[str, str] = {
    # Infantry (all "none" armor)
    "e1": "none", "e2": "none", "e3": "none", "e4": "none", "e6": "none", "e7": "none", "medi": "none", "mech": "none", "spy": "none", "thf": "none", "shok": "none", "dog": "none",
    # Vehicles
    "1tnk": "heavy", "2tnk": "heavy", "3tnk": "heavy", "4tnk": "heavy", "v2rl": "light",
    "jeep": "light", "apc": "heavy", "arty": "light", "harv": "heavy", "mcv": "light",
    "ftrk": "light", "mnly": "heavy", "ttnk": "light", "ctnk": "light", "stnk": "light",
    "qtnk": "heavy", "dtrk": "light", "mgg": "heavy", "mrj": "heavy", "truk": "light",
    # Aircraft
    "heli": "light", "hind": "light", "mh60": "light", "tran": "light", "yak": "light", "mig": "light",
    # Ships
    "ss": "light", "dd": "heavy", "ca": "heavy", "pt": "heavy", "lst": "heavy", "msub": "light",
}

# Armor for buildings
BUILDING_ARMOR: dict[str, str] = {
    "fact": "wood", "powr": "wood", "apwr": "wood", "barr": "wood", "tent": "wood", "proc": "wood", "weap": "wood", "dome": "wood", "fix": "wood", "atek": "wood", "stek": "wood", "hpad": "wood", "afld": "wood", "spen": "wood", "syrd": "wood", "silo": "wood", "kenn": "wood",
    # Defenses
    "pbox": "heavy", "hbox": "heavy", "gun": "heavy", "ftur": "heavy", "tsla": "heavy", "agun": "heavy", "sam": "heavy",
    # Other
    "gap": "heavy", "iron": "wood", "pdox": "wood", "mslo": "wood",
}

# ────────────────────────────────────────────────────────────────────────────
# Unit costs (from Valued: Cost: in rules YAML)

UNIT_COST: dict[str, int] = {
    # Infantry
    "e1": 100, "e2": 150, "e3": 300, "e4": 300, "e6": 400, "e7": 1800, "medi": 200, "mech": 500, "spy": 500, "thf": 500, "shok": 350, "dog": 200,
    # Vehicles
    "1tnk": 700, "2tnk": 850, "3tnk": 1150, "4tnk": 2000, "v2rl": 900,
    "jeep": 500, "apc": 850, "arty": 850, "harv": 1100, "mcv": 2000,
    "ftrk": 600, "mnly": 800, "ttnk": 1350, "ctnk": 1350, "stnk": 1000,
    "qtnk": 2000, "dtrk": 2500, "mgg": 1000, "mrj": 1000, "truk": 500,
    # Aircraft
    "heli": 2000, "hind": 1500, "mh60": 1500, "tran": 900, "yak": 1350, "mig": 2000,
    # Ships
    "ss": 950, "dd": 1000, "ca": 2400, "pt": 500, "lst": 500, "msub": 2000,
}

BUILDING_COST: dict[str, int] = {
    "fact": 2000, "powr": 300, "apwr": 500, "barr": 500, "tent": 500,
    "proc": 1400, "weap": 2000, "dome": 1500, "fix": 1200, "atek": 1500,
    "stek": 1500, "hpad": 500, "afld": 500, "spen": 800, "syrd": 1000,
    "silo": 150, "kenn": 200, "pbox": 600, "hbox": 750, "gun": 800,
    "ftur": 600, "tsla": 1200, "agun": 800, "sam": 700, "gap": 800,
    "iron": 2000, "pdox": 1500, "mslo": 2500,
}

# ────────────────────────────────────────────────────────────────────────────
# Weapon effectiveness (Versus %)
#
# Each entry maps armor_type → multiplier (1.0 = 100% normal damage).
# Derived from OpenRA/mods/ra/weapons/*.yaml Versus: sections.
# Non-combat units have empty dict (cannot attack).

UNIT_EFFECTIVENESS: dict[str, dict[str, float]] = {
    # ── Infantry ────────────────────────────────────────────────────
    "e1": {"none": 1.5, "light": 0.4, "heavy": 0.1, "wood": 0.3, "concrete": 0.1},
    "e2": {"none": 0.6, "light": 0.25, "heavy": 0.25, "wood": 1.0, "concrete": 1.0},
    "e3": {"none": 0.1, "light": 0.34, "heavy": 1.0, "wood": 0.74, "concrete": 0.5},
    "e4": {"none": 0.7, "light": 0.4, "heavy": 0.2, "wood": 0.8, "concrete": 0.1},
    "e6": {},
    "e7": {"none": 10.0, "light": 0.1, "heavy": 0.1, "wood": 5.0, "concrete": 5.0},
    "medi": {},
    "mech": {},
    "spy": {"none": 0.1, "light": 0.01, "heavy": 0.01, "wood": 0.01, "concrete": 0.01},
    "thf": {},
    "shok": {"none": 10.0, "light": 1.0, "heavy": 0.6, "wood": 0.73, "concrete": 1.0},
    "dog": {"none": 5.0, "light": 0.0, "heavy": 0.0, "wood": 0.0, "concrete": 0.0},

    # ── Vehicles ────────────────────────────────────────────────────
    "1tnk": {"none": 0.32, "light": 1.16, "heavy": 0.48, "wood": 0.52, "concrete": 0.32},
    "2tnk": {"none": 0.3, "light": 0.75, "heavy": 1.15, "wood": 0.75, "concrete": 0.5},
    "3tnk": {"none": 0.3, "light": 0.75, "heavy": 1.15, "wood": 0.75, "concrete": 0.5},
    "4tnk": {"none": 0.65, "light": 0.68, "heavy": 0.69, "wood": 0.74, "concrete": 0.5},
    "v2rl": {"none": 0.9, "light": 0.7, "heavy": 0.4, "wood": 0.75, "concrete": 1.0},
    "jeep": {"none": 1.5, "light": 0.3, "heavy": 0.1, "wood": 0.1, "concrete": 0.1},
    "apc": {"none": 1.5, "light": 0.3, "heavy": 0.1, "wood": 0.1, "concrete": 0.1},
    "arty": {"none": 0.6, "light": 0.6, "heavy": 0.25, "wood": 0.4, "concrete": 0.5},
    "harv": {},
    "mcv": {},
    "ftrk": {"none": 0.4, "light": 0.6, "heavy": 0.1, "wood": 0.1, "concrete": 0.2},
    "mnly": {},
    "ttnk": {"none": 10.0, "light": 1.0, "heavy": 1.0, "wood": 1.0, "concrete": 1.0},
    "ctnk": {"none": 0.1, "light": 0.34, "heavy": 1.0, "wood": 0.74, "concrete": 0.5},
    "stnk": {"none": 0.1, "light": 0.34, "heavy": 1.0, "wood": 0.74, "concrete": 0.5},
    "qtnk": {},
    "dtrk": {},
    "mgg": {},
    "mrj": {},
    "truk": {},

    # ── Aircraft ────────────────────────────────────────────────────
    "heli": {"none": 0.3, "light": 0.9, "heavy": 1.0, "wood": 0.9, "concrete": 1.0},
    "hind": {"none": 1.44, "light": 0.72, "heavy": 0.28, "wood": 0.6, "concrete": 0.28},
    "mh60": {"none": 1.44, "light": 0.72, "heavy": 0.28, "wood": 0.6, "concrete": 0.28},
    "tran": {},
    "yak": {"none": 1.0, "light": 0.6, "heavy": 0.25, "wood": 0.5, "concrete": 0.25},
    "mig": {"none": 0.3, "light": 0.9, "heavy": 1.15, "wood": 0.9, "concrete": 1.0},

    # ── Ships ───────────────────────────────────────────────────────
    "ss": {"none": 0.0, "light": 0.75, "heavy": 1.0, "wood": 0.75, "concrete": 5.0},
    "dd": {"none": 0.36, "light": 0.66, "heavy": 1.2, "wood": 0.88, "concrete": 0.6},
    "ca": {"none": 0.6, "light": 0.6, "heavy": 0.25, "wood": 0.35, "concrete": 1.0},
    "pt": {"none": 0.28, "light": 0.72, "heavy": 1.0, "wood": 0.72, "concrete": 0.48},
    "lst": {},
    "msub": {"none": 0.8, "light": 0.48, "heavy": 0.3, "wood": 0.5, "concrete": 1.0},

}

# Defense structures (for disruption dimension)
DEFENSE_EFFECTIVENESS: dict[str, dict[str, float]] = {
    "pbox": {"none": 1.5, "light": 0.3, "heavy": 0.1, "wood": 0.1, "concrete": 0.1},
    "hbox": {"none": 1.5, "light": 0.3, "heavy": 0.1, "wood": 0.1, "concrete": 0.1},
    "gun": {"none": 0.2, "light": 0.75, "heavy": 1.0, "wood": 0.5, "concrete": 0.5},
    "ftur": {"none": 0.9, "light": 0.5, "heavy": 0.25, "wood": 0.5, "concrete": 0.2},
    "tsla": {"none": 10.0, "light": 1.0, "heavy": 1.0, "wood": 0.6, "concrete": 1.0},
    "agun": {"none": 0.0, "light": 1.0, "heavy": 0.0, "wood": 0.0, "concrete": 0.0},
    "sam": {"none": 0.0, "light": 1.0, "heavy": 0.0, "wood": 0.0, "concrete": 0.0},
}

# ────────────────────────────────────────────────────────────────────────────
# Special unit roles

ECONOMIC_UNITS = {"harv", "truk"}
ECONOMIC_BUILDINGS = {"proc", "silo"}
PRODUCTION_BUILDINGS = {"barr", "tent", "weap", "hpad", "afld", "spen", "syrd", "kenn"}
TECH_BUILDINGS = {"dome", "atek", "stek", "fix"}
POWER_BUILDINGS = {"powr", "apwr"}

NON_COMBAT_UNITS = {
    utype for utype, vs in UNIT_EFFECTIVENESS.items() if not vs
}


# ────────────────────────────────────────────────────────────────────────────
# Query functions


def get_effectiveness(attacker_type: str, target_armor: str) -> float:
    """Get damage multiplier for an attacker against a target armor type.

    Args:
        attacker_type: Unit type (e.g., "e3", "1tnk").
        target_armor: Armor type (e.g., "none", "heavy").

    Returns:
        Damage multiplier (1.0 = normal, >1 = effective, <1 = weak).
        Returns 0.0 if unit cannot attack.
    """
    vs = UNIT_EFFECTIVENESS.get(attacker_type.lower(), {})
    if not vs:
        return 0.0
    return vs.get(target_armor.lower(), 1.0)


def get_unit_vs_unit(attacker: str, target: str) -> float:
    """Get effectiveness of attacker against a specific target unit."""
    target_armor = UNIT_ARMOR.get(target.lower(), "none")
    return get_effectiveness(attacker, target_armor)


def get_unit_armor(unit_type: str) -> str:
    """Get armor type for a unit. Returns 'none' if unknown."""
    return UNIT_ARMOR.get(unit_type.lower(), "none")


def get_building_armor(building_type: str) -> str:
    """Get armor type for a building. Returns 'wood' if unknown."""
    return BUILDING_ARMOR.get(building_type.lower(), "wood")


def get_unit_cost(unit_type: str) -> int:
    """Get cost of a unit. Returns 0 if unknown."""
    return UNIT_COST.get(unit_type.lower(), 0)


def get_building_cost(building_type: str) -> int:
    """Get cost of a building. Returns 0 if unknown."""
    return BUILDING_COST.get(building_type.lower(), 0)


def can_attack(unit_type: str) -> bool:
    """Check if a unit type can attack."""
    return bool(UNIT_EFFECTIVENESS.get(unit_type.lower(), {}))


def is_economic_target(unit_or_building: str) -> bool:
    """Check if destroying this target causes economic disruption."""
    t = unit_or_building.lower()
    return t in ECONOMIC_UNITS or t in ECONOMIC_BUILDINGS


def is_production_target(building_type: str) -> bool:
    """Check if destroying this building disrupts production."""
    return building_type.lower() in PRODUCTION_BUILDINGS


def is_tech_target(building_type: str) -> bool:
    """Check if destroying this building causes tech regression."""
    return building_type.lower() in TECH_BUILDINGS


def is_power_target(building_type: str) -> bool:
    """Check if destroying this building disrupts power supply."""
    return building_type.lower() in POWER_BUILDINGS


def compute_army_counter_score(
    own_units: list[dict],
    enemy_units: list[dict],
) -> tuple[float, float]:
    """Compute how well an army counters the enemy army.

    Args:
        own_units: List of dicts with at least 'type' key.
        enemy_units: List of dicts with at least 'type' key.

    Returns:
        (counter_score, vulnerability_score) both in [0, 1].
        counter_score: fraction of own combat units effective vs enemy.
        vulnerability_score: fraction of own combat units vulnerable to enemy.
    """
    if not own_units or not enemy_units:
        return 0.5, 0.5

    enemy_armors: dict[str, int] = {}
    for u in enemy_units:
        armor = get_unit_armor(u.get("type", ""))
        enemy_armors[armor] = enemy_armors.get(armor, 0) + 1

    total_enemy = sum(enemy_armors.values())
    if total_enemy == 0:
        return 0.5, 0.5

    own_combat = [u for u in own_units if can_attack(u.get("type", ""))]
    if not own_combat:
        return 0.0, 1.0

    effective_count = 0
    vulnerable_count = 0

    for u in own_combat:
        utype = u.get("type", "")
        avg_eff = 0.0
        for armor, count in enemy_armors.items():
            avg_eff += get_effectiveness(utype, armor) * (count / total_enemy)

        if avg_eff >= 1.0:
            effective_count += 1
        elif avg_eff < 0.5:
            vulnerable_count += 1

    n = len(own_combat)
    return effective_count / n, vulnerable_count / n
